id: I4538D229
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:23:15+00:00'
last_modified: '2022-06-08T09:27:34.164052+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105920
  title: མཐུན་ལུང་བཤད་གྲྭའི་སློབ་དེབ་ལེགས་བཤད་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་གཟིངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F88C:
      image_group_id: I1PD105922
      title: ''
      total_pages: 248
      order: 1
      base_file: F88C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
